### ISSUE TITLE
Domain

### ISSUE THREAD

**Issue by fernandoalmeida** [fatiapp/discussions#1]
Which domain will we use?

- fati.io
- fati.app
- fatiapp.com
- fati.life
- fati.tech
- fati.ai

Registration services:

- https://www.dynadot.com/domain/io.html
- https://www.namecheap.com/domains/registration/cctld/io.aspx

**Comment by adrianolisboa** [comment]
- fati.io
- fati.app

Sounds better to me.

**Comment by fernandoalmeida** [comment]
I prefer fati.io, but @squiter have a good argument in favor of fatiapp.com... he believes (and I agree) it would be better for general users (non dev).

**Comment by adrianolisboa** [comment]
Make sense for me. If it's okay for everyone else let's move with it 👍

**Comment by fernandoalmeida** [comment]
Considering that it is an open source project, maybe we would like to use fatiapp.org instead fatiapp.com.

**Comment by squiter** [comment]
I like fatiapp.org, sound good for me.... maybe we can register fati.io in the future... 🤔

**Comment by fernandoalmeida** [comment]
fatiapp.org registered! :wink:
